/**
 * Marathon Coach v2 — SQLite Schema
 *
 * AI-first architecture: plans stored as JSON blobs generated by Gemini,
 * with individual workouts extracted for easy querying.
 *
 * Legacy tables (strava_tokens, strava_activity_detail) kept for
 * backward compatibility with existing Strava sync pipeline.
 */

// ─── v2 Core Tables ─────────────────────────────────────────

export const CREATE_USER_PROFILE = `
CREATE TABLE IF NOT EXISTS user_profile (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  name TEXT,
  age INTEGER NOT NULL,
  gender TEXT NOT NULL CHECK (gender IN ('male', 'female')),
  weight_kg REAL,
  vdot_score REAL NOT NULL,
  max_hr INTEGER,
  rest_hr INTEGER,
  current_weekly_miles REAL NOT NULL,
  longest_recent_run REAL NOT NULL,
  experience_level TEXT NOT NULL CHECK (experience_level IN ('beginner', 'intermediate', 'advanced')),
  race_date TEXT NOT NULL,
  race_name TEXT,
  race_course_profile TEXT DEFAULT 'unknown',
  race_goal_type TEXT DEFAULT 'finish',
  target_finish_time_sec INTEGER,
  injury_history TEXT DEFAULT '[]',
  known_weaknesses TEXT DEFAULT '[]',
  scheduling_notes TEXT,
  available_days TEXT NOT NULL DEFAULT '[1,2,3,4,5,6]',
  long_run_day INTEGER NOT NULL DEFAULT 0,
  weight_source TEXT DEFAULT 'manual',
  weight_updated_at TEXT,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);`;

export const CREATE_TRAINING_PLAN = `
CREATE TABLE IF NOT EXISTS training_plan (
  id TEXT PRIMARY KEY,
  plan_json TEXT NOT NULL,
  coaching_notes TEXT,
  key_principles TEXT,
  warnings TEXT,
  vdot_at_generation REAL NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'abandoned')),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);`;

export const CREATE_WORKOUT = `
CREATE TABLE IF NOT EXISTS workout (
  id TEXT PRIMARY KEY,
  plan_id TEXT NOT NULL REFERENCES training_plan(id),
  week_number INTEGER NOT NULL,
  day_of_week INTEGER NOT NULL,
  scheduled_date TEXT NOT NULL,
  workout_type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  target_distance_miles REAL,
  target_pace_zone TEXT,
  intervals_json TEXT,
  status TEXT NOT NULL DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'completed', 'skipped', 'modified', 'partial')),
  original_distance_miles REAL,
  modification_reason TEXT,
  strava_activity_id INTEGER,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);`;

export const CREATE_TRAINING_WEEK = `
CREATE TABLE IF NOT EXISTS training_week (
  id TEXT PRIMARY KEY,
  plan_id TEXT NOT NULL REFERENCES training_plan(id),
  week_number INTEGER NOT NULL,
  phase TEXT NOT NULL,
  target_volume REAL NOT NULL,
  actual_volume REAL NOT NULL DEFAULT 0,
  is_cutback INTEGER NOT NULL DEFAULT 0,
  ai_notes TEXT,
  UNIQUE(plan_id, week_number)
);`;

export const CREATE_PERFORMANCE_METRIC = `
CREATE TABLE IF NOT EXISTS performance_metric (
  id TEXT PRIMARY KEY,
  workout_id TEXT REFERENCES workout(id),
  strava_activity_id INTEGER,
  date TEXT NOT NULL,
  distance_miles REAL NOT NULL,
  duration_minutes REAL NOT NULL,
  avg_pace_sec_per_mile REAL,
  avg_hr INTEGER,
  max_hr INTEGER,
  splits_json TEXT,
  best_efforts_json TEXT,
  perceived_exertion INTEGER,
  gear_name TEXT,
  strava_workout_type INTEGER,
  source TEXT NOT NULL DEFAULT 'strava' CHECK (source IN ('strava', 'manual')),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);`;

export const CREATE_COACH_MESSAGE = `
CREATE TABLE IF NOT EXISTS coach_message (
  id TEXT PRIMARY KEY,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,
  message_type TEXT NOT NULL DEFAULT 'chat' CHECK (message_type IN ('chat', 'briefing', 'analysis', 'digest', 'plan_change')),
  metadata_json TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);`;

export const CREATE_AI_CACHE = `
CREATE TABLE IF NOT EXISTS ai_cache (
  id TEXT PRIMARY KEY,
  cache_type TEXT NOT NULL,
  cache_key TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(cache_type, cache_key)
);`;

export const CREATE_APP_SETTINGS = `
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);`;

export const CREATE_SHOES = `
CREATE TABLE IF NOT EXISTS shoes (
  id TEXT PRIMARY KEY,
  strava_gear_id TEXT UNIQUE,
  name TEXT NOT NULL,
  brand TEXT,
  total_miles REAL NOT NULL DEFAULT 0,
  max_miles REAL NOT NULL DEFAULT 500,
  retired INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);`;

// ─── Legacy Tables (kept for Strava sync + backup compat) ───

export const CREATE_STRAVA_TOKENS = `
CREATE TABLE IF NOT EXISTS strava_tokens (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL,
  expires_at INTEGER NOT NULL,
  athlete_id INTEGER NOT NULL,
  athlete_name TEXT,
  connected_at TEXT NOT NULL DEFAULT (datetime('now')),
  last_sync_at TEXT
);`;

export const CREATE_STRAVA_ACTIVITY_DETAIL = `
CREATE TABLE IF NOT EXISTS strava_activity_detail (
  id TEXT PRIMARY KEY NOT NULL,
  performance_metric_id TEXT NOT NULL,
  strava_activity_id INTEGER NOT NULL UNIQUE,
  splits_json TEXT,
  laps_json TEXT,
  hr_stream_json TEXT,
  pace_stream_json TEXT,
  elevation_gain_ft REAL,
  calories INTEGER,
  cadence_avg REAL,
  suffer_score INTEGER,
  device_name TEXT,
  best_efforts_json TEXT,
  gear_id TEXT,
  gear_name TEXT,
  perceived_exertion INTEGER,
  strava_workout_type INTEGER,
  moving_time_sec INTEGER,
  elapsed_time_sec INTEGER,
  polyline_encoded TEXT,
  summary_polyline_encoded TEXT,
  distance_stream_json TEXT,
  elevation_stream_json TEXT,
  cadence_stream_json TEXT,
  time_stream_json TEXT,
  segment_efforts_json TEXT,
  timezone TEXT,
  utc_offset INTEGER,
  activity_name TEXT,
  activity_type TEXT,
  description TEXT,
  FOREIGN KEY (performance_metric_id) REFERENCES performance_metric(id)
);`;

// ─── Health Data ──────────────────────────────────────────────

export const CREATE_HEALTH_SNAPSHOT = `
CREATE TABLE IF NOT EXISTS health_snapshot (
  id TEXT PRIMARY KEY,
  date TEXT NOT NULL,
  resting_hr INTEGER,
  hrv_rmssd REAL,
  sleep_hours REAL,
  resting_hr_trend_json TEXT,
  hrv_trend_json TEXT,
  sleep_trend_json TEXT,
  weight_kg REAL,
  vo2max REAL,
  respiratory_rate REAL,
  respiratory_rate_trend_json TEXT,
  spo2 REAL,
  spo2_trend_json TEXT,
  steps INTEGER,
  signal_count INTEGER NOT NULL DEFAULT 0,
  cached_at TEXT NOT NULL
);`;

export const CREATE_HEALTH_DATE_INDEX = `
CREATE UNIQUE INDEX IF NOT EXISTS idx_health_date ON health_snapshot(date);`;

// ─── Indexes ────────────────────────────────────────────────

export const CREATE_WORKOUT_DATE_INDEX = `
CREATE INDEX IF NOT EXISTS idx_workout_date ON workout(scheduled_date);`;

export const CREATE_METRIC_DATE_INDEX = `
CREATE INDEX IF NOT EXISTS idx_metric_date ON performance_metric(date);`;

export const CREATE_COACH_MESSAGE_INDEX = `
CREATE INDEX IF NOT EXISTS idx_coach_message_created ON coach_message(created_at);`;

// ─── All Tables (order matters for foreign keys) ────────────

export const ALL_TABLES = [
  CREATE_USER_PROFILE,
  CREATE_TRAINING_PLAN,
  CREATE_TRAINING_WEEK,
  CREATE_WORKOUT,
  CREATE_PERFORMANCE_METRIC,
  CREATE_COACH_MESSAGE,
  CREATE_AI_CACHE,
  CREATE_APP_SETTINGS,
  CREATE_SHOES,
  CREATE_STRAVA_TOKENS,
  CREATE_STRAVA_ACTIVITY_DETAIL,
  CREATE_HEALTH_SNAPSHOT,
  CREATE_WORKOUT_DATE_INDEX,
  CREATE_METRIC_DATE_INDEX,
  CREATE_COACH_MESSAGE_INDEX,
  CREATE_HEALTH_DATE_INDEX,
];
